import { zodResolver } from '@hookform/resolvers/zod'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useForm } from 'react-hook-form'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { z } from 'zod'

import { ErrorNotice, PageHeader } from '../components/Ui'
import { api } from '../lib/api'
import type { ConnectionType, Device, Paginated, Site } from '../lib/types'

const schema = z.object({ site_id: z.string().uuid('Select a site'), device_uid: z.string().min(1, 'Device UID is required'), name: z.string().min(1, 'Device name is required'), description: z.string(), device_type: z.string().min(1, 'Device type is required'), manufacturer: z.string(), model: z.string(), firmware_version: z.string(), connection_type: z.enum(['WIFI', 'ETHERNET', 'CELLULAR', 'LORA', 'OTHER']) })
type Values = z.infer<typeof schema>

export function DeviceFormPage() {
  const { deviceId } = useParams(); const [params] = useSearchParams(); const editing = Boolean(deviceId); const navigate = useNavigate(); const queryClient = useQueryClient()
  const sites = useQuery({ queryKey: ['sites', 'options'], queryFn: () => api<Paginated<Site>>('/sites?page_size=100&is_active=true') })
  const device = useQuery({ queryKey: ['device', deviceId], queryFn: () => api<Device>(`/devices/${deviceId}`), enabled: editing })
  const blank = { site_id: params.get('site_id') ?? '', device_uid: '', name: '', description: '', device_type: 'ESP32', manufacturer: '', model: '', firmware_version: '', connection_type: 'WIFI' as ConnectionType }
  const { register, handleSubmit, formState: { errors } } = useForm<Values>({ resolver: zodResolver(schema), values: device.data ? { site_id: device.data.site_id, device_uid: device.data.device_uid, name: device.data.name, description: device.data.description ?? '', device_type: device.data.device_type, manufacturer: device.data.manufacturer ?? '', model: device.data.model ?? '', firmware_version: device.data.firmware_version ?? '', connection_type: device.data.connection_type } : undefined, defaultValues: blank })
  const mutation = useMutation({ mutationFn: (values: Values) => api<Device>(editing ? `/devices/${deviceId}` : '/devices', { method: editing ? 'PUT' : 'POST', body: JSON.stringify(Object.fromEntries(Object.entries(values).map(([key, value]) => [key, value === '' && ['description', 'manufacturer', 'model', 'firmware_version'].includes(key) ? null : value]))) }), onSuccess: async (result) => { await queryClient.invalidateQueries({ queryKey: ['devices'] }); navigate(`/devices/${result.id}`) } })
  return <><PageHeader title={editing ? 'Edit device' : 'Register device'} description="Connect a permanent device identity to one of your sites." />{mutation.error ? <ErrorNotice error={mutation.error} /> : null}<form className="panel max-w-3xl space-y-5" onSubmit={handleSubmit((values) => mutation.mutate(values))}><div className="grid gap-5 sm:grid-cols-2"><label className="field-label">Site<select className="input" {...register('site_id')}><option value="">Select a site</option>{sites.data?.items.map((site) => <option key={site.id} value={site.id}>{site.name}</option>)}</select><span className="field-error">{errors.site_id?.message}</span></label><label className="field-label">Device UID<input className="input" placeholder="ESP32-A8C339" {...register('device_uid')} /><span className="field-error">{errors.device_uid?.message}</span></label><label className="field-label">Device name<input className="input" {...register('name')} /><span className="field-error">{errors.name?.message}</span></label><label className="field-label">Device type<input className="input" placeholder="ESP32" {...register('device_type')} /><span className="field-error">{errors.device_type?.message}</span></label><label className="field-label sm:col-span-2">Description<textarea className="input min-h-24" {...register('description')} /></label><label className="field-label">Manufacturer<input className="input" {...register('manufacturer')} /></label><label className="field-label">Model<input className="input" {...register('model')} /></label><label className="field-label">Firmware version<input className="input" {...register('firmware_version')} /></label><label className="field-label">Connection type<select className="input" {...register('connection_type')}>{['WIFI', 'ETHERNET', 'CELLULAR', 'LORA', 'OTHER'].map((value) => <option key={value}>{value}</option>)}</select></label></div><p className="text-sm text-slate-400">New devices start in PROVISIONING. Online status will be managed by a later MQTT phase.</p><div className="flex gap-3"><button className="button-primary" disabled={mutation.isPending}>{mutation.isPending ? 'Saving…' : 'Save device'}</button><Link className="button-secondary" to={editing ? `/devices/${deviceId}` : '/devices'}>Cancel</Link></div></form></>
}
